### ISSUE TITLE
Cannot assign multiple profile types

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#1002]
While Mozilla community can have multiple roles, Mozilla Pulse can only allow one profile type for each profile.

Example: Some fellows go on to become Open Leaders mentors or even staff. However, I can only choose one profile type.

**Comment by ithompson4** [comment]
Hello @acabunoc. Could you please provide more details concerning the multiple profiles types you would like to see, and the fields within each. Could you also provide a link to the Mozilla community website that allows different profile types to be selected. Thank you.

**Comment by xmatthewx** [comment]
Thanks @ithompson4 - This issue requires a bit of thinking about how this is structured before we jump into the code. Check out [help wanted](https://github.com/mozilla/network-pulse/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted+%3Awave%3A%22) and [good first issue](https://github.com/mozilla/network-pulse/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue+%3Aoctocat%3A%22) for things more ready to go. 

For this, I think we also need to address the setup of both roles and programs, and their relationship to profiles. They have a similar limit. 

@acabunoc - For roles, my thinking was that these shift from fellow to staff. For programs, I'd expect them to be more loose and overlapping. I see a few approaches, but I get stuck because I think we have to expect this stuff to _not_ be maintained. We could let people collect program tags and have many that they might keep forever. I wonder if we should include a year when someone gains a tag.

I'm inclined to keep roles limited to paid/contracted relationships like staff, fellow, grantee. And use programs for wranglers, mentors, etc. Is that too fuzzy of a distinction?

**Comment by acabunoc** [comment]
The distinction makes sense, but you'll still run into the issue with multiple roles if a grantee goes on to be a fellow or staff. Would it be easier to treat them all as controlled tags and not try to add a distinction?

**Comment by xmatthewx** [comment]
> you'll still run into the issue with multiple roles if a grantee goes on to be a fellow or staff

I'd guess that you can only have 1 current official status. You're no longer a grantee, now you're staff. So we can switch it.  

> Would it be easier to treat them all as controlled tags and not try to add a distinction?

Maybe so! We do have a need to filter and display staff and fellows with a level of reliability that's a bit different than other program relationships. The original ideas was that staff should be able to create those program relationships freely as they see fit. But the more formal roles would be fixed and centrally controlled.

**Comment by gideonthomas** [comment]
we have a separate ticket for this, closing
