### ISSUE TITLE
Create models for pulse entry types

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/network-pulse#1030]
We want to support different types of content on pulse in the form of extending our existing infrastructure / model system to support this as opposed to creating something entirely new.

Entry types are [mentioned here](https://docs.google.com/document/d/1LITsvpTJaafsyGuVrNeE27Sz_XY1Ase2D8IWCmu7dLk/edit?ts=5cadf65b#heading=h.p4wvs4fhqwpl).

cc @Pomax and @youriwims and @xmatthewx

**Comment by Pomax** [comment]
The easiest would obviously be a "type" field on the Entry model, with a string to indicate what kind of entry it is, but it might be worth putting in a bit more work and creating an entry type model that can indicate which of each "thing" mentioned in the table applies to that type, with a ForeignKey added to our Entry model that lets us set that entry's type. This would also allow us to get an entry with the associated type's "which fields are required, which are optional, which are meaningless" and then use that to tailor the entry presentation for the user at the API-consuming side (e.g. by Pulse)

**Comment by gideonthomas** [comment]
@Pomax what is the type field foreign key? i.e. what does that model look like?

**Comment by xmatthewx** [comment]
I don’t know the best approach. But some things to consider below. I don't think I'm saying anything out of line with what you're proposing, just thought some goals might be helpful. Ignore me if it's not.
 - search: can this remain efficient across types? I don't think we want to silo
 - fallback: we should consider a core type, a fallback when none is specified
 - similar: types are more similar than different, seems good to inherit commonality, track differences.
 - simplicity: we essentially want authors and viewers to be able to distinguish similar but different items in our catalog. my gut says there's a single table with all entries, with a means to distinguish them on i/o, rather than different tables for each type. but now I've completely strayed from goals to implementation. So, I'll stop and say adios.

**Comment by gideonthomas** [comment]
@Pomax are you able to draft up some kind of simple model relationship visual based on the comments above?

**Comment by Pomax** [comment]
We're contrained a little by Django in this case: while in plain Python one class can "overrule" what the parent doesn, in Django that is explicitly forbidden, so we can't create do a kind of "progressively more permission" model inheritance in which the "requiredness" changes between two models. Concretely, an entry with a required URL cannot be extended to a more specific entry type in which the URL is no longer required. And vice versa (an entry in which URL is optional cannot be extended to a more specific entry type in which the URL is required).

So while the classical hierarchy would be great, it's not an option that's available =(

However, looking at https://stackoverflow.com/a/43168682 it seems like we might have wiggle room by using a simple `type` field, but then using different serializers for each type, with the Entry model encoding the minimal required data set and optional-everything-else, and then serializers then making sure that when date comes in, it conforms to the needs of whatever the indicated entry type should be.

I'll have to dig a bit more, but that might be a way forward that doesn't even require new database tables.

**Comment by alanmoo** [comment]
Would that approach merely be more fields on the existing entry then, coupled with a few custom serializers?

**Comment by Pomax** [comment]
correct, except even less than that: it would add a single `entry_type` (name tbd) field on the Entry model, plus however many custom serialisers to match the [type definitions table](https://docs.google.com/document/d/1LITsvpTJaafsyGuVrNeE27Sz_XY1Ase2D8IWCmu7dLk/edit?ts=5cadf65b#heading=h.p4wvs4fhqwpl), with the get and post views updated to switch serializer based on that new field.
