### ISSUE TITLE
Entry content structure

### ISSUE THREAD

**Issue by youriwims** [mozilla/network-pulse#1136]
Mavis mentioned that having the 'why interesting' section directly after the entry description with no visual difference could create an odd content flow (see https://github.com/mozilla/network-pulse/pull/1130#discussion_r314527595).

What do you think? @natalieworth @xmatthewx 

cc: @mmmavis 

Related Issues/PR: #1079 #1030

**Comment by xmatthewx** [comment]
Good catch. And, this is actually intentional and how it's always been. The two fields for `description` and `why interesting` exist just to help guide people to write better descriptions with their audience in mind. It was easier than explaining to people how to write a quality description with help text. Does that make sense? If not, feel free to reopen.
