### ISSUE TITLE
Build detail view 

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#14]
> Detail view (follow pattern on http://mozilla.github.io/clubs-events/)

**Comment by kristinashu** [comment]
I think this would need to be designed first. I would also like to explore alternatives to using a light box since they're pretty old school and not great on mobile.

I also question the need to even have a detail view. The clubs reporter tool is a good reference but it is different than what we're trying to do (I think). It contains all the info/content within the app vs the Pulse which links out to different sites so it would require 2 clicks vs 1 to get to the really content.

**Comment by mmmavis** [comment]
+1 I personally don't like lightboxes either. 

I'm not sure what additional info we would have on the details view - that probably also depends on the design for the thumbnail view too. But one benefit with having details view is that the url to a specific artifect/story etc can be easily shared out.

**Comment by kristinashu** [comment]
Ah good points about thumbnail info and urls. I guess we need to figure out what the artifacts will be to know what info to include.

**Comment by xmatthewx** [comment]
I'll follow your lead on lightbox vs not. 

We will need the ability for users to share a link to an individual item. Following that link will require a view of a single item.

We are currently gathering more info than we display. And, there's an interest in more tags/metadata that would be supplied by staff post-submission (issue, program, type, audience), more than we would want to display in the gallery view. It _could_ remain hidden and just used for search, but is probably nice to share. 

@mmmavis – does the unknown style of this display prevent you from preparing the plumbing? Can we work on design and dev in tandem, more an agile approach than waterfall?

**Comment by mmmavis** [comment]
Done in PR https://github.com/mozilla/network-pulse/pull/25. It definitely needs some design love but we can file follow-up tickets instead. Just wanted to get the feature in place first. Gonna close this ticket now! 🍻
