### ISSUE TITLE
Draft plan to engage and test with Program staff

### ISSUE THREAD

**Issue by acabunoc** [mozilla/network-pulse#22]
Let's look at the research doc!

**Comment by xmatthewx** [comment]
Here's a table that lists some motivations and incentives of [sharing a thing](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.oyht0d998skd), though it currently focuses more on network members rather than staff. 

Here's another table that gets at some motivation for [Input and Browsing](https://docs.google.com/document/d/1SAAuPgOaVqpQorrbD0vZSnf8wHHYjddPyYrkrFj72kQ/edit#heading=h.2eurb6etse1u). Not very extensive.  

We could refine these and then work them into the summary deck.

**Comment by xmatthewx** [comment]
Depends on #48. Should also inform #17.

**Comment by acabunoc** [comment]
Plan drafted here: https://docs.google.com/document/d/1IUbYB56ZlwCand-R1TSdMNixatOPw207cQX1D1EBBL8/edit#
