### ISSUE TITLE
Notice to Twitter

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#247]
When a new item lands on Pulse, or when  new item is featured, it'd be great to notify people in Chat, on Twitter, etc. 

 - What's the idea flow? Frequency of messages?
 - What does the notice say?

Let's think about these things and then hand it over the engineers for input.

**Comment by kristinashu** [comment]
Instead of posting every time an item is added to pulse, we could do it when we have X amount of new posts (ex. Over 3 new items have been added to Pulse. Take a look mzl.la/pulse). Down side of this would be that we won't be able to include names of the items.

We could still post every time a new item is Featured (ex. "Teaching Kit: Combating Cyber Violence Against Women and Girls" was just featured on Pulse. Have a look mzl.la/pulse). My only concern would be that a featured post probably would have been recently Chatted/Tweeted out when it was first added to Pulse, so might be redundant. 

For now, we should only post to Chat, maybe in the Town Square channel. Once we've expand beyond staff, then we could also Tweet it.

**Comment by xmatthewx** [comment]
Okay. Let's start with a notice on Chat. We can initially post all new items, dial back to featured if it proves to be too much. This notice will also alert staff to look and see if a thing should be featured. 

We can implement twitter later. We're not quite there yet. I wouldn't worry, however, about redundancy. Most of these things don't land on twitter from Mozilla, because Mozilla doesn't yet know about these things. That's a key problem this platform aims to address. We could make an account just for Pulse. People can choose to follow it or not. Our official channels can retweet our auto tweet if it's interesting.

**Comment by kristinashu** [comment]
Do you have anything in mind for what the notification should say? I think it should include the name of the asset. 

cc @mmmavis any concerns with implementing this?

**Comment by mmmavis** [comment]
We will need some backend experts to chime in here 😉 @Pomax @cadecairos @gideonthomas 

Can we trigger mozbot so that every time a new entry is submitted to Pulse mozbot then notifies people in the Town Square channel on Chat?

**Comment by cadecairos** [comment]
We can write a webhook for that!

**Comment by xmatthewx** [comment]
We've got a notice to Slack now. Would be cool to explore a bot for Twitter too. Probably just for featured things. cc @phillipadsmith

**Comment by phillipadsmith** [comment]
@xmatthewx Happy to set-up a simple Twitter bot, if that's not stepping on someone's toes! 👍  Let me know if you have a preferred handle, avatar, etc.

**Comment by phillipadsmith** [comment]
Feel free to assign this issue to me.

**Comment by xmatthewx** [comment]
@KevZawacki - we'd like to have Pulse send Featured items (not all items) to Twitter automatically. Can you help set up the twitter account? I think you should probably own it so you can track follows, retweets, and replies. True?

**Comment by KevZawacki** [comment]
Hi @xmatthewx, I'd advise against creating a new Twitter handle for Pulse. Lotta and I are working to consolidate Mozilla social handles, rather than create new ones. 

As the operator of twitter.com/mozilla, I can instead make a habit of tweeting a Pulse project once or twice a week from there. It'll reach our 192,000 followers. 

Thoughts?

**Comment by phillipadsmith** [comment]
@KevZawacki If it's helpful, I can create a #mozilla-pulse-featured channel in Slack that you could subscribe to for a reminder...?

**Comment by Pomax** [comment]
For what is effectively a datastream, postings for which we don't explicitly initiate, I'd actually advise to use a separate twitter handle. Many other services do this too, where the "main, human controlled" account is an obvious account, but service feed accounts are separate, so you don't pollute what is a meaningful stream of communication and outreach with autogenerated feed data.

**Comment by xmatthewx** [comment]
@KevZawacki – I definitely don't want to pollute your effort to consolidate and align. The idea with a handle like this would be to provide a feed for you, staff and others who want to see it all. Could even have Bot in the name to make/description to make it clear that it wouldn't be a space for interaction.

We can try a Slack channel for Featured + manual posting for now, but maybe we can find some time to discuss over video with Jesse and Lotta.

**Comment by KevZawacki** [comment]
@phillipadsmith No worries -- I've added a reminder to my calendar. 

@xmatthewx Got it. Sound like a decision @Lottarao can weigh in on.

**Comment by Pomax** [comment]
We have a pulse channel set up in Slack that gives staff a clear place to listen for updates to the stream. Closing this for now, and if we decide we want more external advertisement (a la planet mozilla) we can file a new issue specifically for the medium/avenue in question.
