### ISSUE TITLE
Discuss Back link from detail view

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#250]
@mmmavis mentioned some challenges with hooking up the back link to browser history to return a user to the view that brought them to a item detail (search, issue, etc). 

I mentioned in chat that would could probably drop that link if the browser back button worked. I'm less sure now. On Android, users can use the back button easily, even if they save to homescreen (currently set to fullscreen). On iphone, I'm not sure they'll have a way back. Let's consider common ux patterns, and make sure the experience is good quality.

**Comment by kristinashu** [comment]
I think the back button is necessary because otherwise the landing screen and the detail view look too identical to each other when a user first lands on the screen:
<img width="587" alt="screen shot 2016-12-15 at 10 31 38 am" src="https://cloud.githubusercontent.com/assets/1068783/21236936/cada8064-c2b1-11e6-8d24-15a0d5b1659f.png">

**Comment by alanmoo** [comment]
I feel like "featured" shouldn't be highlighted when on a detail view, and then the pages won't look so similar. It'll also give a more accurate hint as to where people are within the site, since the URL isn't going to be `/featured/entryName`, it'll just be `/entries/entryName` or something. Users can then either use the browser back button (which is more available than one we manually put on the page), or they can tap a filter to go to the list. 

The browser back button's management of state handles a lot of edge cases for us that putting in an additional button requires us to reimplement. For example, what happens if a user lands right on a pulse listing via a link? Then we have to not show the back button? What if one detail view links to another? Showing the page itself in different states depending on where the user came from doesn't seem like ideal UX. We should embrace this being on the web and let the browser handle the things it's good at for us.

**Comment by xmatthewx** [comment]
Sounds like we'll remove the back link, leverage browser back, and help people in easy ways where possible (maintain search query, maintain scroll position).

While the community of people who build web apps is smaller than the groups who build native apps and web sites, someone must have written a blog post on best practices. If not, let's write it!!

**Comment by kristinashu** [comment]
Invision has a blog post [Usability Checklist for Web Apps](http://blog.invisionapp.com/usability-checklist-for-web-apps/) that briefly touches on:
"Include Go back to… somewhere close to the top of the screen. Notice that Go back to the product list works much better than just Go back—it has an action verb and clearly states where the user came from."

**Comment by alanmoo** [comment]
I think that's reasonable if we have an information architecture that supports it, like a messaging app where the logical back action from a message is to a list of messages. However, I'm still not convinced it makes sense given the current IA and url structure.

**Comment by xmatthewx** [comment]
Let's keep this open after we land the next build. See how it feels.

**Comment by kristinashu** [comment]
I'm going to close this and say that it is something we should test https://github.com/mozilla/network-pulse/issues/421
