### ISSUE TITLE
Input form

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#257]
We will soon move from google form to a our own frontend for the db. Let's do a quick pass on the design...
 - What patterns do we want keep or change from the current form ui/ux? (including error handling)
 - How will we handle adding one or more creators as discreet?
 - How will we handle tags?
 - Some indication that your name is attached as submitter. 
 - Image upload (hopefully there's a module for cropping that doesn't require design. probably not mvp) 

cc @alanmoo

**Comment by kristinashu** [comment]
Here's a first pass at the form: https://redpen.io/nvd9c7a75f06c79e35

It's based on the current form and the updates determined in https://github.com/mozilla/network-pulse/issues/236

The styling is based on Bootstrap 4 http://v4-alpha.getbootstrap.com/content/reboot/#forms

cc @mmmavis

**Comment by mmmavis** [comment]
@kristinashu lovely! How do we wanna show error message / indicate invalid input? How do other MoFo sites handle it?

**Comment by kristinashu** [comment]
Thanks @mmmavis! For the form fields, we can style the same as Bootstrap:

<img width="560" alt="screen shot 2017-01-04 at 11 05 42 am" src="https://cloud.githubusercontent.com/assets/1068783/21655306/553563a2-d26e-11e6-9f32-7bf11e42d397.png">

Would inline validation be an option?

Are there any other possible errors? Not user errors but if there is a backend error or connection problem while a user is submitting.

I'll mockup what a successful form submission should look like as well.

**Comment by mmmavis** [comment]
@Pomax @alanmoo 
For client side validation I think having inline error messages sounds good. What should we do if the backend server is down? Do we wanna show some sort of feedback message upon form submission?

**Comment by alanmoo** [comment]
Yeah, maybe an error by the submit button?

**Comment by Pomax** [comment]
If there is no backend server disabling the form and showing an error that the service is currently unavailable feels like something internet users would be familiar with - it's easy enough to test for since the form needs to ask the server for a unique form id anyway. If it can't reach the server at that point, then submitting later won't really do much even if the server does come back up after a few seconds.

**Comment by kristinashu** [comment]
I've added a comp with the error warnings and got a bunch of design feedback at crit today. Please also add any comments/feedback you may have https://redpen.io/ov0d7f8ba9c437ee56

**Comment by Pomax** [comment]
I see that the redpen has a unified field for listing creators/contributors/partners distinct from the person posting the entry, but we only have 'creators' as a recognized role in the backend. Are all three effectively synonymous with "creator", or are the distinctions between the three roles that will be important for our users such that we need to preserve that information?

If not, it might be better to use a single label with a different noun, and match that noun in the backend model for this category of person, to prevent developer confusion, and potentially user confusion when people submit data around different roles, only to be presented with the stored data as "everyone is marked as creator".

**Comment by kristinashu** [comment]
There's no distinction between creators/contributors/partners so having just the one field type works. For wording, we could say something like "Who are the creators? This could be staff, contributors, partners..."

Note that there is a difference between the person adding the project to Pulse ("Post by)" and the person (or people) who originally made the thing that is being posted.

**Comment by alanmoo** [comment]
Then I'd agree we need a different noun. Best I can come up with off the top of my head is "contact person"

**Comment by kristinashu** [comment]
How about "author"?

**Comment by Pomax** [comment]
Yeah, "author" feels like a reasonable unification noun.

**Comment by xmatthewx** [comment]
This is just in code, not user facing? If so, sounds good.

**Comment by Pomax** [comment]
A user facing change will also be necessary though: if we only have one field, that we label with one label when you view entries, then we should use that same label for when you submit an entry. A subtext that explains that we mean "creators, contributors, partners, etc" with that label makes sense of course, but we should not be setting an expectation that people are filling in data with a level of detail that we then throw away when they submit that data.

**Comment by kristinashu** [comment]
I think there was a misunderstanding, I think I get it now.

**1) The user who is logged in and is adding a post to Pulse can stay as is.** 

- Backend it is called "Entry.published_by"
- User sees "Post by" 
<img width="195" alt="screen shot 2017-01-11 at 9 30 27 am" src="https://cloud.githubusercontent.com/assets/1068783/21859249/c3b439da-d7e0-11e6-89dd-e756d1d461e2.png">

**2) The form field where an author says who worked on the project is what needs clarification.** 

- Backend it is called "creator"
- User currently sees "Who are the creators, contributors, and partners?". But engineers were worried this is confusing because the backend only has "creator" while the users sees "creator", "contributor" and "partners". I recommend we keep the backed as "creator" and update the form to “Who are the creators? This could be staff, contributors, partners…”. This way staff, contributors, partners are all seen as creators. Will that work for everyone?

<img width="552" alt="screen shot 2017-01-11 at 9 22 47 am" src="https://cloud.githubusercontent.com/assets/1068783/21858991/d81ac746-d7df-11e6-8b75-5c7e5860b8da.png">

**Comment by Pomax** [comment]
@kristinashu nice summary! This sounds like a good solution.

**Comment by kristinashu** [comment]
Closing this ticket and opened an implementation ticket https://github.com/mozilla/network-pulse/issues/309
