### ISSUE TITLE
Add heart to fav view list

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#288]

**Comment by aayushsanghavi** [comment]
I'd like to take this issue

**Comment by aayushsanghavi** [comment]
Where should the heart icon be placed? Just beside the title of the project item or in the extreme right part of the div?

**Comment by aayushsanghavi** [comment]
![screenshot from 2017-01-06 20 23 38](https://cloud.githubusercontent.com/assets/19590302/21721402/3d5bea4e-d44e-11e6-8834-353cb4914b31.png)
I've implemented the issue as above. Would you like to suggest changes in the view or is it fine?

**Comment by xmatthewx** [comment]
I defer to @kristinashu, but I'd guess we'll align to right side of the card to follow the pattern on the detail view. https://redpen.io/wx0ef253b2c39028d1

**Comment by kristinashu** [comment]
Thank you @aayushsanghavi for helping out it this! 

Yes, the hearts will be more consistent with the rest of the site if they line up of the right side.
![3d5bea4e-d44e-11e6-8834-353cb4914b31](https://cloud.githubusercontent.com/assets/1068783/21726195/8b6cbe56-d3f0-11e6-802f-4ebf99428855.jpg)

**Comment by aayushsanghavi** [comment]
Okay, I'll fix that and make a pull request

**Comment by mmmavis** [comment]
For v1, I think it makes sense to use list style layout since favs page can get super long as we show ALL faved project at once. 

For v2 we have the "view more" button (https://pulse-react.herokuapp.com/latest scroll to page bottom to find the button) and therefore it solves the super long page problem. I wonder for consistency reason if we should use cards on favs page (vs list style)? Note that we are going to make [Search page to display project cards](https://github.com/mozilla/network-pulse/issues/291) as well.

Here's a screencap of Favs, in list style (WIP, heart icons haven't been added)

![page-shot-2017-1-6 mozilla network pulse](https://cloud.githubusercontent.com/assets/2896608/21737552/c5f87b30-d42e-11e6-8e70-5960fa07f302.png)

For me, seeing only the title, creator, and a date doesn't provide enough clues to relate to a project that I fav'ed. 👀 

Thoughts?

**Comment by xmatthewx** [comment]
I'm open to either. 

The change from cards to a list for Favs came from a suggestion by another friendly designer, not something we observed in users. I don't think we know yet if/how people will use the Favs list. I do agree with @mmmavis that the new card style addresses the original problem that prompted the list.

@kristinashu - what do you think?

**Comment by kristinashu** [comment]
Sure, stick with the new cards.

**Comment by mmmavis** [comment]
Cool, I'll update & close https://github.com/mozilla/network-pulse/issues/289 . 😉

**Comment by xmatthewx** [comment]
Hi @aayushsanghavi – thanks for all of your work on this (#315). It's great to see your progress. The Pulse v2 is also proceeding well. I wanted mention that the work you're doing on this v1 branch won't likely show up when we launch v2. We are glad for you to continue your work for the learning experience, but I just wanted to make sure that was clear. Please let us know if you have any questions. 

After this, we could help identify some tickets for v2 that might be interesting for you. 

Thanks again.

cc @ryanwarsaw

**Comment by aayushsanghavi** [comment]
Hi @xmatthewx, its been great working with you'll. If I'm not mistaken you'll are shifting to a React based v2; I'm aware of that. I didn't know React so I thought of working on issues that didn't use it and I learnt a lot in the process. Currently, I'm learning React so that I could contribute to Pulse other Mozilla projects that use it. I must say, you guys are very supportive and helping. Looking forward to working on other issues as well.

**Comment by mmmavis** [comment]
`v1` is now retired. Gonna close this ticket now.

Thanks for offering your help @aayushsanghavi ! 😉
