### ISSUE TITLE
Migrate data to real backend

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#295]

**Comment by Pomax** [comment]
can we add some guide test and concrete steps to this issue? (which data specifically, which backend specifically, how many steps are involved in the entire process?)

**Comment by mmmavis** [comment]
@alanmoo @Pomax 

Data currently lives on Google Spreadsheet: https://docs.google.com/spreadsheets/d/1vmYQjQ9f6CR8Hs5JH3GGJ6F9fqWfLSW0S4dz-t2KTF4/edit We would like to "migrate" it over to our real database. I'm not sure what type of database we have for Pulse backend. I assume we cannot simply use the "download as csv" feature that Google Spreadsheet provides and import the csv into the database. Any suggestion on how to approach this? If it helps, I can grab and modify the data processor Python script that we used for MozFest schedule app (this is a script to turn Google Spreadsheet data into a JSON file).

**Comment by mmmavis** [comment]
@Pomax , @alanmoo, and I talked about this briefly on chat. Here's the summary

> Pomax: it's probably easiest to export to CSV, then write a quick python or node script to read that in and do database inserts
(as reading in CSV is trivially easy in pretty much any language)

we can't simply do something like http://www.postgresqltutorial.com/import-csv-file-into-posgresql-table/ suggests because

> Pomax: We can't, because we're not writing plain SQL data, we're writing django-managed data
2:48 PM
so the script would probably be a .py script that reads in the CSV, fires up our django instance, and then fires off "blah.create" calls

**Comment by mmmavis** [comment]
I think we can close this one? @alanmoo

**Comment by xmatthewx** [comment]
I believe there are new entries to migrate. Can we file something that does that and turns off current form simultaneously? @alanmoo

**Comment by alanmoo** [comment]
Created #358
