### ISSUE TITLE
Build "add new entry" form

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#309]
Based on design in https://github.com/mozilla/network-pulse/issues/257

Comps: https://redpen.io/p/nzcd35d57dd04ad6dc

Basic styling is based on Bootstrap 4 http://v4-alpha.getbootstrap.com/content/reboot/#forms
but errors are styled a little different.

**Comment by mmmavis** [comment]
What do we show if a user is not logged in and he/she clicks on the "+" icon or visits `/add` page directly? @kristinashu

**Comment by kristinashu** [comment]
It should link to Google's Sign in page.

**Comment by mmmavis** [comment]
@kristinashu Should we hide the "+" icon if user is already on the /add page?

**Comment by xmatthewx** [comment]
Probably so. Related: https://github.com/mozilla/network-pulse/issues/316

**Comment by kristinashu** [comment]
Excellent point @mmmavis! Yes, please hide the + icon when on /add page.

**Comment by mmmavis** [comment]
Things I have to do related to the submission form

- [ ] form UI
- [ ] form Validation
- [ ] post and error handling

**Comment by mmmavis** [comment]
Design: https://redpen.io/ov0d7f8ba9c437ee56

What should we show someone who's currently logged in but decides to click on the `Sign Out` link. We don't have a dedicated logout page and clicking on the `sign out` link will sign user out immediately. On the favs page we are just doing an inline text change (https://github.com/mozilla/network-pulse/issues/318) but `/add` can only be accessible by a logged in user.

/cc @kristinashu @Pomax @alanmoo @xmatthewx

**Comment by xmatthewx** [comment]
a redirect to Featured would indicate a state change. @kristinashu - would that feel natural?

**Comment by kristinashu** [comment]
Yeah, I think bring the user to the Featured page works.

**Comment by mmmavis** [comment]
Hey @Pomax , 😃  

I'm tempted to grab a copy of https://github.com/mozilla/learning.mozilla.org/blob/master/pages/clubs/form/builder/Form.jsx and work from there. One thing I need to change is to show error message inline, just below the field (see [mock up](https://redpen.io/ov0d7f8ba9c437ee56)) instead of aggregating all error messages together. Since Pulse's form is a lot simpler than Learning site's I'm also planning on simplifying `Form.jsx` a bit (e.g., no need to have the `getProgress()` method etc) What do you think? Does that sound like a plan or I should just write my own or use existing packages (if that's the case, do you have any recommendation?)

**Comment by Pomax** [comment]
if you're going to grab it, I'd say "don't simplify" but instead see what we can *add* to make it do what you need. For progress, I'd say let's add a `checkprogress={true/false}` so that the Form can check `this.props.checkprogress`. For showing errors next to their respective fields, that should also be pretty easy, we can add a control property for that too and then in the code see if they need to be shown alongside or aggregated. 

And then we really need to publish this as a library on npm, not keep it loose files, so we can use that here in network pulse, and in learning.mozilla.org

**Comment by Pomax** [comment]
I've set up https://github.com/Pomax/react-formbuilder so we can work on this in its own repo.

**Comment by mmmavis** [comment]
@Pomax cool I'll submit PRs on https://github.com/Pomax/react-formbuilder.

**Comment by gvn** [comment]
@Pomax Weren't we planning on putting it into `mofo-ui`?

**Comment by Pomax** [comment]
@gvn we never ended up doing so, though, so given its utility it feels pretty useful to publishing it as npm lib in its own right and then simply have mofo-ui include it as dependency, expose it to mofo code bases. That way the code a much larger surface for the rest of the world to also do something meaningful with without strictly tying it to a mofo ui, which kind of makes sense: at its core this is still just a form builder, which React desperately needs a few more of.

**Comment by mmmavis** [comment]
I gotta keep the ball rolling so I'm gonna start by contributing to https://github.com/Pomax/react-formbuilder. So far I have submitted 1 PR and created a few tickets 😁.

[Club form on Learning site](https://learning.mozilla.org/clubs/apply/) and [Pulse's new entry form](https://redpen.io/ov0d7f8ba9c437ee56) have different UX and UI so I'm not sure how I can make the library work for both (and many more future scenarios). 👀 Should designers and devs meet first before we start turning the Learning site form code into a library so that future projects can use it? I'm not familiar with the code so I can't gauge how much time I will need to make the library work at least for both Learning site and Pulse. @Pomax can you shine a light 🔦 ? If it takes long I wonder if we should get a simple form working on Pulse first?

**Comment by Pomax** [comment]
I'd say see what you need on the pulse side first. I would be highly surprised if this code already covers both use cases but I would be equally surprised if we can made the code generic enough to cover both, given that it only cares about generating a form element with some prebuilt validation. What they looks like it's entirely up to site-specific styling. I'm back on Saturday, so I can do a bit of parallel cleanup and making the code a bit more accommodating on Sunday

**Comment by mmmavis** [comment]
@Pomax I added more tickets to the "react-formbuilder" repo. I'm still in the process of understanding the source code so apologize if I added tickets for things that have been already taken care of. 

Let's meet next week (when we are back to the same timezone 😄) to talk about the library we are building here!

**Comment by Pomax** [comment]
no worries. Meeting next week sounds like a plan!

**Comment by mmmavis** [comment]
@Pomax @xmatthewx @kristinashu :bowtie: 

I wanna suggest having a basic HTML form that relies on browser validation first while we work on Pomax's [`react-formbuilder`](https://github.com/Pomax/react-formbuilder) so it can eventually be used and styled like the mockup for Pulse. Work on the library side is ongoing but I'm having trouble gauging how much time we need to make it configurable enough for Pulse. 2 big things that are blocking us from launch (I think there are only 2?) are this form and [search page improvement](https://github.com/mozilla/network-pulse/pull/348). @xmatthewx am I correct we are doing pilot test with Moz Staff for v2 launch first? If so I wanna suggest that we finish this 2 big things first, launch v2, and continue working on Pulse to make it better (the form especially). Sorry for having this dragging!


One side note:
I think we should get rid of v1 staging, update `master` branch (currently use as v1 staging) with code in `react` branch, and set up a real staging for v2+. (I will create a ticket for this.)

**Comment by Pomax** [comment]
sounds good to me. I'm finishing up the "multiple instance for this thing" in the form builder atm so it can deal with how this project wants to do the "creators" field(s), and the inline error reporting rather than aggregated at the bottom. So it should be ready for use probably on Monday

**Comment by mmmavis** [comment]
@Pomax wow that's great to hear! I'm not sure what's on your plate so I don't wanna keep pinging you about the form builder library. I would try submitting PRs but it would def take a lot longer (dev + code review) that's why I suggested in my comment above to have a simple HTML form first 😁 If we can have the form builder library ready for Pulse to use early next week I think we can aim for having the "pretty form" for the v2 launch.

**Comment by Pomax** [comment]
form-builder *is* my plate today

**Comment by mmmavis** [comment]
✏️ 📄 🔨

**Comment by Pomax** [comment]
multiplicity has been added with you set as reviewer, inline reporting needs a bit more work.

**Comment by xmatthewx** [comment]
> If so I wanna suggest that we finish this 2 big things first, launch v2, and continue working on Pulse to make it better (the form especially). 

@mmmavis that sounds like a good plan. It would be very helpful if staff could start posting to v2, even if the form is pretty basic. Other people won't use that in the near future.

**Comment by Pomax** [comment]
we can use form-builder already, as the only thing left on that is "where the error reporting" for fields is right now. That doesn't get in the way of the functional form, and mavis and I can work in parallel today to respectively write the form, and make sure form-builder understands an `inline-warning={true}` instruction for showing errors next to the associated field.

**Comment by mmmavis** [comment]
@kristinashu where are we sending users to after a successful form submission?

**Comment by kristinashu** [comment]
Can it bring them to the post they just added?

**Comment by Pomax** [comment]
That's an interesting question. I think to make that happen the POST response needs to tell the user the `id` of the entry that it built, which it doesn't do right now. We only say `{status: "submitted"}` [right now](https://github.com/mozilla/network-pulse-api/blob/master/pulseapi/entries/views.py#L201) but we can probably change that so that it replies with `{status: "submitted", id: 123456}` on a processed submission.

**Comment by mmmavis** [comment]
Form is ready for QA: http://network-pulse-staging.herokuapp.com/add . Please create new tickets for suggestion and feedback. I'm gonna close this ticket now. Yay team!

**Comment by kristinashu** [comment]
Form is looking good! I've opened a ticket for some styling things but none of them are blockers for launch https://github.com/mozilla/network-pulse/issues/374

**Comment by xmatthewx** [comment]
thanks @mmmavis!!!!! thanks team. excited to try this.
