### ISSUE TITLE
Discuss user accounts

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#311]
We have a few overlapping topics related to user accounts. Can we gather those here for a meta discussion?

 - Favs – are these available for non-auth users?
 - Domains
   - we'll initially restrict to @mozilla email users. Can we whitelist others? Can others use Favs?
   - what happens to a user from another domain who can't login? 
 - Login/Logout – login is critical for adding items, useful for favs, but _not_ necessary for most visitors. How much prominence should this have UX-wise? Can we rely on prompts rather than header real estate? 

I've probably missed some discussion by the team on these topics and others. Forgive any mistaken assumptions.

Edit: What do we need to figure out now? What can test and revise later?

**Comment by alanmoo** [comment]
> useful for favs, but *necessary* for most visitors

Typo or intentional? If the latter, can you clarify? Seems counter to the second point.

**Comment by xmatthewx** [comment]
Typo! _Not_ necessary. Corrected above.

**Comment by Pomax** [comment]
Would it be possible to clarify on whether this is about "what we do now", "what we've implemented now", or "what we want to end up for MVP"?

Answering these points base on the work we've done/are doing for the new network-pulse-API implementation:

-Favs:  I'd very much like us to pick a more appropriate word for "favorites" to remove ambiguity around what the expected behaviour is. are we implementing bookmarking (in which case, we do not have that implemented right now in the new network pulse api backend), or are we implementing a "meets approval" signal (currently implemented in the backend)? 
- Domains:
  - domain restrictions are in place for integrity and statistics purposes. Integrity in terms of being reasonably sure that people in the mozilla domain will not be hammering our API (fave toggling with a bot, for instance), and statistics in terms of counting "faves": we have these implemented to act like appreciation votes at the moment and so for useful stats getting anonymous counts in there would not tell us much about the value of entries to our network
  - we are still implementing that, the current idea is to support the same "redirect to the URL the user was on when they clicked login" functionality. Whether or not the login succeeded can be verified by any of the "user only" api server endpoints, so clients can tell whether login succeeded or not that way, or we can add a dedicated `/user/status` or the like that clients can call specifically to see if there is an authenticated session.
- Login/logout: I'd vote for "subtle, but easy to find when a user looks for it". It's not the main functionality for users of our front end, so it doesn't need to be very prominent, but it should be found in a location where user eyes tend to move when they start looking for a login option. That one thing I would insist on though (insofar as that is reasonable for me to do of course =D) is to make sure the user can *always* tell that they're logged in and who they are logged in as, if they are logged in. This acts both as reassuring signal ("I am recognized") and as giving the user context for their UI (differences in the UI based on invisibly being logged in are hard to reconcile if there is only one mental model)

**Comment by alanmoo** [comment]
I agree with @pomax's points. A few things to add:

* Favs: we can still do the localStorage thing for non-authenticated users. We don't currently have an endpoint for non-authed users to increase a count of fav'd entries. But also, everything @pomax said is something I agree strongly with.

* For users who can't log in it depends on front end implementation, but I'd suggest some sort of messaging somewhere to let people know this, be it before or after login attempt is something I don't have any opinions on.

**Comment by Pomax** [comment]
One important question when we do go with localStorage bookmarking is how to make it explicit that those bookmarks are not synced in any way, and when to put them in the database when the user does end up logging in.

In the anonymous case, perhaps a one-time "you've just bookmarked an entry without being signed in - you will only be able to see your bookmarks on this device/in this browser. Please log in if you want to be able to access your bookmarks on other devices". notice might be necessary.

The anonymous->logged-in transition also comes with a possible challenge: while the client can tell that an anonymous user with a localStorage collection of bookmarks has succeeded in logging in, and can thus communicate to the API server that those bookmarks should be properly recorded in the database, the user logging in might not actually be the user who favourited entries... as a use case: someone bookmarking entries as anonymous user, and going 'hey friend who also uses this, can you log in for me so I can ...' resulting in their bookmarks getting recorded as if they're their friend's bookmarks. So going from anonymous to logged-in might require some UI asking the user whether they want to store their bookmarks in the database, or whether to not do that this time round?

**Comment by alanmoo** [comment]
That dialog might be useful once we give everyone the ability to log in, but for now, I'd think not so much?

As for the transition problem: I we'd be happy if that becomes a problem, no? Similar to your first suggestion though, we could simply ask when people log in if they'd like to sync favorites from this computer to their account.

**Comment by xmatthewx** [comment]
Summary from our discussion on video. Please flag any mistakes.

Issue to file [ @mmmavis @kristinashu  ]
 - failed login screen/model

## Versions & Privileges

### v1 (current production)

staff, non-staff, anonymous
 - no login
 - post
 - save favs locally

### v2.0 (in development)

admin (via django)
 - moderate
 - delete dups
 - manage users

staff (user)
 - login (w/ @mozilla @mozillafoundation email)
 - post
 - save & sync favs

network member & anonymous
 - no login
 - no posting
 - save favs locally


### v2.2 (future)

admin (via django)
 - same as v2.0 above

staff (user)
 - same as v2.0 above

network member (user)
 - login
 - posting needs approval
 - save & sync favs

anonymous
 - no login
 - no posting
 - save favs locally

**Comment by kristinashu** [comment]
Opened a ticket for failed Sign in https://github.com/mozilla/network-pulse/issues/313

Is this ticket good to close?
