### ISSUE TITLE
Implement Sign in failed screen

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#317]
Based on design in #313 

Icon of person: 
[icon-user.svg.zip](https://github.com/mozilla/network-pulse/files/717508/icon-user.svg.zip)

<img width="401" alt="screen shot 2017-01-19 at 10 58 37 am" src="https://cloud.githubusercontent.com/assets/1068783/22120937/b195ea9e-de36-11e6-9585-22d3bb68ab13.png">

**Comment by mmmavis** [comment]
@kristinashu can you export the icon and put it here https://drive.google.com/drive/folders/0B2irLVDJivhLVE8wMXdENW5CTXc ? 🍻

**Comment by kristinashu** [comment]
Added! It's called icon-user.svg

**Comment by mmmavis** [comment]
We might want to edit the error message a bit so it's more descriptive for non Mozilla Staff. See https://github.com/mozilla/network-pulse-api/issues/59 for context. 👀

**Comment by Pomax** [comment]
I'm not sure how much more descriptive we can get - the current message is "Sign in failed. Only Mozilla staff can login now as we test this new platform. Check back soon!" which seems to exactly cover what happened: we're going to pilot v2 to people with a mozilla login only, so people trying to log in with a not-mozilla account getting a rejection notice after running through google oauth seems reasonable. We can't influence the google oauth process to prevent certain emails from even starting the process (oauth is not a login system itself, it is purely an authentication system, in which users tell google to tell us that google vouches for these users being who they say they are), so people will be getting rejected at the end, where this notice covers why their login failed.

Did you have a specific, better message in mind?

**Comment by mmmavis** [comment]
Um I was thinking about the use case where 

- I first try to log in using a personal non Mozilla account
- I get rejected and see "Signin failed this platform is only for Mozilla Staff to test for now" message
- I then want to log in using a Mozilla account instead

At this point there's no option for me to have another login attempt since I've already been identified by Pulse API as a Non-staff user.  I won't see an "log out" option on Pulse UI since my initial signin attempt failed. The only way to bring up the "log in" option on Pulse again is to first go to a Google service page to log out from Google and then visit Pulse again.

Anyways, as a user I don't have lots of experience using sites or apps that use Google oAuth so I can't tell if the above flow is typical or intuitive. 😜

**Comment by Pomax** [comment]
This seems like a perfectly fine discovery path? You tried to log in with a non-moz email, the app told you it was only for moz, you realised you used the wrong email =)

**Comment by xmatthewx** [comment]
I think it's okay for most users and use cases. We could add a text link to "Sign in"  below the "Explore featured" button.

**Comment by xmatthewx** [comment]
Just tried it. I have two recommendations while @kristinashu travels. 

1) Link below button (my color is probably wrong)
2) Emphasis on the notice. For now, a bold phrase. Maybe we can design a pattern for notices like this. 

<img width="412" alt="screenshot 2017-01-30 10 39 00" src="https://cloud.githubusercontent.com/assets/53411/22429428/90cb5380-e6d8-11e6-9d92-f93d960fa519.png">

**Comment by mmmavis** [comment]
Gonna close this ticket now since the "sign in failed" screen has been implemented. To test, go on https://pulse-react.herokuapp.com/add and try signing in using a non Mozilla account.

Let's create followup tickets instead for design changes (if any).

🍻
