### ISSUE TITLE
"postcss" node package does not work on Windows

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#323]
We should try to find an alternative or at least have a note on README first.

**Comment by Pomax** [comment]
notes don't do much when colleagues need things to work in order to do review, so I would highly recommend *not* running any postcss browser compatibility fixed for development, with a special npm tasks like `npm run compat` that does include the postcss for testing in older browser. The majority of dev is on current Firefox/Chrome/Safari/etc so shouldn't need the "last 3 browsers" fixes that postcss is being used for.

**Comment by Pomax** [comment]
supposedly, [this should work](https://github.com/ai/browserslist/issues/109#issuecomment-274280967):
```
{
  "private": true,
  "dependencies": {
    "autoprefixer": "^6.5.4",
    "post-css": "^...."
  },
  "browserslist": [
    "> 1%",
    "last 2 versions"
  ],
  "scripts": {
    "prefix": "postcss --use autoprefixer *.css -d build/autoprefixer css/main.css"
  }
}
```

**Comment by mmmavis** [comment]
Fixed.
