### ISSUE TITLE
Add loading spinner

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#364]
Search is nice and snappy. On slow connections, a spinner to indicate something is happening would be useful. 

~~depends on https://github.com/mozilla/network-pulse/issues/361~~

**Comment by mmmavis** [comment]
@xmatthewx I edited the ticket description since this does not depend on #361. It's somewhat related to #361 but this can sure be tackled separately.

On MozFest schedule app we have this "loading dots" animation. I think we can just use the same animation here. @kristinashu thoughts?

![loading-animation](https://cloud.githubusercontent.com/assets/2896608/22999112/a4e16324-f38e-11e6-97fd-8f8fd549968d.gif)

**Comment by xmatthewx** [comment]
That works for me. 

No need to tackle this now @mmmavis. I tried your search experience throttled with dev tools ... it's pretty snappy until you get to super slow connections. I don't think this is a launch blocker.

**Comment by mmmavis** [comment]
oh yea I'm not gonna work on any enhancement tickets for now. 😃
