### ISSUE TITLE
Change "Sign In" <button> on /favs page to <a>

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#365]
This is more for code improvement.

https://github.com/mozilla/network-pulse/blob/master/pages/bookmarks.jsx#L39-L41. The "sign in" button on /favs page should probably be an anchor instead. Since ultimately it's a link that redirects to the external login URL (see https://github.com/mozilla/network-pulse-api#get-loginoriginal_urlurl).

**Comment by Pomax** [comment]
Technically it's not a navigation link: users are not intentionally going to "a url", they are intentionally logging in, which happens to use redirects but they couldn't care less really, so in this case a button is fine, as long as it can be tabbed to for accessibility purposes, so I think what we want here is to preserve the button, but make sure it has a `tabIndex=0` so that it's a keyboard-navigable element in the browser.

**Comment by mmmavis** [comment]
Based on [our discussion](https://github.com/mozilla/network-pulse/pull/415#discussion_r105238840) current code is good as is. Gonna close this ticket now.
