### ISSUE TITLE
UI label for "tags" in "add new entry" form

### ISSUE THREAD

**Issue by mmmavis** [mozilla/network-pulse#375]
Brought up by @Pomax in https://github.com/mozilla/network-pulse/pull/372#issuecomment-281495955

> Tags are called "keywords", and they're shown as using hashtags... Is that the intention? Do we strip the hashtags when we send to the API? Do we present searches based on tags with `#` injected back in? This seems like a thing we should probably change so that we at least tell people not to use hashtags?

> ![screenshot 169](https://cloud.githubusercontent.com/assets/177243/23187058/49b8869e-f83e-11e6-9aa7-79b7e67b06bd.png)

Good point. Currently hash(#) gets stripped before form gets submitted to Pulse API. So we are really posting an array of "tags" to Pulse API. I'm thinking maybe we should just call it "tag" on both frontend and backend (it already is on backend) to make everything consistent. On the form instead of having just one single input field maybe we can have something like what we have for the creator field(s)?

<img width="650" alt="screen shot 2017-02-22 at 11 36 30 am" src="https://cloud.githubusercontent.com/assets/2896608/23228909/32a0b002-f8f3-11e6-9ac6-171d40aa581f.png">
(but using "tag" instead of "name")

/cc @kristinashu @xmatthewx

**Comment by Pomax** [comment]
Another common practice is to let people type words and automatically convert a word into a tag (visually) on a space or a comma or the like.

**Comment by alanmoo** [comment]
We've also got the autocomplete API for this purpose, i.e. https://network-pulse-api-staging.herokuapp.com/tags/?search=a

**Comment by Pomax** [comment]
also note that react-formbuilder lets you use arbitrary components, so if there is an `AutoComplete` component that can be used, the following should work:
```
let AutoComplete = require('blah/auto-complete'),;
tags: {
  type: AutoComplete,
  ...
}
```

**Comment by mmmavis** [comment]
We should decide soon if we wanna use hashtag or just tag first. Hashtag can only be one word while tags can be multi-word. This will affect how our search functionality works too as searching for `#webliteracy` and `web literacy` are not the same thing. UI/UX improvements can be post-launch enhancement but we should really decide what format we like it to be stored in the database so that we don't run into problems after launch.

**Comment by kristinashu** [comment]
Are we talking about the _keyword tags with the hashtag_ or about the _name field_ for adding creators? 

For _keyword tags with the hashtag_ we could just call them 'tags' instead of keywords. The idea with using a hashtag is that it's a modern way to do tags (people are used to doing it, one after another). Spaces are tricky for users because it isn't clear that something like "web site" will end up as "web" and "site" were as if they use a hashtag they know to use one word "#website". If we used spaces or commons we would need to add text that says" use a comma or a space to separate tags" (like we do in the current google form).

For _name field_ we should stick to "Name" for the hint text. Using "tag" sounds very confusing. The idea for using separate fields is again to save writing the text "use a comma" (spaces wouldn't work here because of the same needed between First Name and Last Name). We are also thinking of eventually having the option of adding a URL to the person or org so having separate fields seems to make sense (not sure how that would be done in one field).

**Comment by kristinashu** [comment]
I am happy to go with whatever is easiest to do right now and then iterate and improve later on...

**Comment by kristinashu** [comment]
and test...

**Comment by mmmavis** [comment]
@kristinashu 

> Are we talking about the keyword tags with the hashtag or about the name field for adding creators?

Oh sorry the reason why I included the screencap of the creator field(s) was just to show my idea of UI improvement **for the hashtag/keyword/tag** field. Didn't meant to suggest any changes to be made to the creator field itself. 😉

**Comment by kristinashu** [comment]
Ah ok that makes more sense! Let's ignore hashtags for now and go with what you suggested @mmmavis (using the + creator field).

**Comment by xmatthewx** [comment]
@alanmoo - does the api expect to receive comma separated tags? Does it expect `#`?

I propose that we launch with what the API expects now and then follow up later.

**Comment by alanmoo** [comment]
The API doesn't care about `#`, it's just taking in strings. So it'll store `#web` and `web` as two different items if that's what it's given. This is entirely a front-end concern.

**Comment by alanmoo** [comment]
(For the record, it accepts an array of strings, so whatever we go with it just slightly changes how they get parsed before submitting.)

**Comment by xmatthewx** [comment]
I'm hesitant to use `#` in this field. As users, we expect to use those in #context, rather than a standalone tags field. We could consider dropping the field and shifting to hashtags in the description. 

I propose we run with comma separated tags for now, and then discuss hashtags post launch. Curious what y'all think.

**Comment by alanmoo** [comment]
I hate #hashtags in #context, because they get #used so #poorly all the #time.

**Comment by Pomax** [comment]
My take on hashtags is that they only make sense in a setting where it is otherwise impossible to tell what is a searchable keyword. They're a necessary evil in tweets and the like, but for our entries we should be able to use real words, since they're already specifically presented as a thing on their own.

**Comment by xmatthewx** [comment]
Any dissenting opinions? 

If not, I think we're good to go with Tags input field with this revised placeholder text: `privacy, internet of things, game, best practice`.

**Comment by mmmavis** [comment]
@Pomax 's react-formbuilder makes it really easy to turn this from one single input box 

<img width="746" alt="screen shot 2017-02-24 at 1 10 23 pm" src="https://cloud.githubusercontent.com/assets/2896608/23321716/721f7db4-fa95-11e6-89da-c6bc20006589.png">

into something like

<img width="754" alt="screen shot 2017-02-24 at 1 14 56 pm" src="https://cloud.githubusercontent.com/assets/2896608/23321725/7ab8f22a-fa95-11e6-911b-b451b2579670.png">

let me know which one you refer @kristinashu @xmatthewx

**Comment by Pomax** [comment]
@mmmavis I would be more in favour of @Alanmoo's suggestion of using an autocomplete/tag component here. People shouldn't have to click on "add another" just to type more than one tag, a comma or space should probably make this happen automatically for them

**Comment by kristinashu** [comment]
@mmmavis do whatever is quickest for you to do now. We can iterate, test and improve on it later. Lets launch this sucker and get some outside eyes on it!

**Comment by Pomax** [comment]
fastest I'd say keep a text field, don't have users type `#` and just split on `value.trim().split(/,\s*/)`

**Comment by xmatthewx** [comment]
Split also on whitespace? So "mozfest 2016, iot" yields three tags [mozfest,2016,iot]? It seems better to ask for commas from users, and then split only on commas so we get things as intended.

**Comment by alanmoo** [comment]
Whitespace after commas. You'll still get ["mozfest 2016","iot"] with that regex.
