### ISSUE TITLE
Possible bug with react-router and analytics

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#409]
When visiting the site, switching to other navigation sections seems to trigger an event in analytics, but the page that's currently active doesn't always get reported correctly. For example, visiting `issues` shows active page as `/issues/` but then switching to `latest` shows `/issues` (notice the lack of final slash). Switching between the main nav items does this inconsistently, sometimes reflecting the correct page, sometimes not.

**Comment by xmatthewx** [comment]
If I understand this correctly, I don't think it is a problem. We would see `/issues/` and `/issues` in analytics, right?

<img width="360" alt="screen shot 2017-04-18 at 4 11 56 pm" src="https://cloud.githubusercontent.com/assets/53411/25150963/c865f500-2451-11e7-9974-00241359b286.png">

**Comment by alanmoo** [comment]
Perhaps, but I'm not sure if the problem manifests itself in another way leading to inaccurate analytics. We should figure out what causes the issue I was seeing and if it might result in other inconsistencies.

**Comment by mmmavis** [comment]
Could be something to do with GA, react-router, and [react-helmet](https://www.google.ca/search?q=react-helmet&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&dcr=0&ei=fN0VWofXBvPs8weNkJVo). I will take a look into this today.

**Comment by mmmavis** [comment]
I wasn't able to reproduce the issue you were seeing @alanmoo ... but I found another issue about mismatching page and page title on GA

e.g., I went to Fav page first and clicked on the Issues link on nav bar to go to the Issues page
<img width="952" alt="screen shot 2017-11-22 at 4 56 54 pm" src="https://user-images.githubusercontent.com/2896608/33155543-30671cb0-cfa6-11e7-8dde-d3e9fda7fbb9.png">

This happens only when you visit a page without page reload. Page title on GA will always be the title of the page you just navigated away from. It seems like this is because`react-helmet` (the library we use to update `document` `head` meta) doesn't update meta on the initial render of a component. `head` meta gets properly updated after we have already sent GA page view event to GA (<- this happens when `react-router` updates its state in response to URL changes) so that causes the mismatching page title problem on GA dashboard. This is probably fixable if I spend time digging through react-router and react-helmet's docs. Not sure how bad this bug is so I'll let @xmatthewx triage this ticket!

**Comment by xmatthewx** [comment]
If Analytics has the correct slug and correct counting, I don't think it is critical. The page titles do look wacky in analytics, crisscrossed a bunch, but this isn't critical if the counting of reported routes are correct.

**Comment by alanmoo** [comment]
Ah, I've noticed that bug in the past too, and I think is partially what I was getting at when filing this one. I think it's worth fixing, but not necessarily high priority. Perhaps you could file another ticket with a clearer description of the problem/what needs to happen to resolve it, and label it "help wanted" before closing this one?

**Comment by xmatthewx** [comment]
Closing. Tracking in #988
