### ISSUE TITLE
Remove link from Title in Detail view

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/network-pulse#457]
The title of an entry links to itself. Maybe it should link to the source material, i.e. the same URL as the "Visit" button at the bottom.

**Comment by Pomax** [comment]
that's a good point. Some thoughts:
- having the title going from "featured" or "latest" to the entry itself makes sense, but since we have a "visit" button at the bottom on the entry itself, keeping the title a link there becomes counter productive.
- Do we also need a "visit" option in the condensed view? Right now you can't just open "all the things on the featured tab" because you have to click through to each one

/cc @mmmavis @xmatthewx

**Comment by xmatthewx** [comment]
In the Detail view, title should just be text, no link (as hinted by pomax). 

Prior design had a Visit button on summary cards. We stepped away from this in tandem with other factors and choices. Let's table this for now, can revisit later after we gather some analytics.

**Comment by mmmavis** [comment]
Titles on detail view should be plain text. Fix was on staging and I forgot to push it to prod until now 😂
