### ISSUE TITLE
Add intro statement

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#488]
Pulse needs an intro statement for some context.

On the Featured view, let's add an intro statement. See green box in image below. 

 - Text: "Discover & collaborate on projects for a healthy internet. [Learn more](https://www.mozillapulse.org/entry/120)."
 - Link: https://www.mozillapulse.org/entry/120 

<img width="1114" alt="screen shot 2017-04-13 at 6 20 14 pm" src="https://cloud.githubusercontent.com/assets/53411/25442670/a5dba4f8-2a73-11e7-9f20-a07192618b61.png">

---

We can use the styles currently applied to "logged-in-status" on the Favs view.

<img width="788" alt="screen shot 2017-04-26 at 11 33 52 am" src="https://cloud.githubusercontent.com/assets/53411/25442904/45fc0a7c-2a74-11e7-97c0-6c454d8022dd.png">

**Comment by xmatthewx** [comment]
We could maybe skip the about page and just
 - link from intro statement and/or footer to entry on [pulse about pulse](https://www.mozillapulse.org/entry/120) 
 - redirect from /about to the entry

**Comment by Sudip7** [comment]
@xmatthewx , could be little precise on the issue, what exactly need to be done.

**Comment by xmatthewx** [comment]
Thanks @Sudip7. I edited the original comment above to make it more clear. Let me know if you have any questions. Thanks for the help!!

**Comment by Pomax** [comment]
@Sudip7, to explain what needs to happen:

you'd be update the featured page's JSX so that it has something along the lines of `<div><p>Discover & collaborate on projects for a healthy internet. <Link ....>Learn more</Link></p></div>` or something (@mmmavis should be able to point you to an example of the code we use for this) in the render function, above the code that generates that generates the page code for all the entries

To find out which page is built using which component, you can look at https://github.com/mozilla/network-pulse/blob/master/routes.jsx - if we check its route mapping, we see that on https://github.com/mozilla/network-pulse/blob/master/routes.jsx#L111 the featured page is generated by https://github.com/mozilla/network-pulse/blob/master/routes.jsx#L20-L32 which tells us that it's actually just a generic ProjectLoader but with the property `featured` set to the string "True"

So, you can edit https://github.com/mozilla/network-pulse/blob/master/components/project-loader/project-loader.jsx and then between https://github.com/mozilla/network-pulse/blob/master/components/project-loader/project-loader.jsx#L131-L132 you can add the code that will render that text + link if `this.props.featured` exists.

You can probably follow the example of `renderTagHeader` and `renderSearchResult`, where you make a new function `renderLearnMoreNotice`, and then return null if this.props.featured isn't set, and if it is, return the notice

**Comment by mmmavis** [comment]
@Sudip7 I replied you on Mattermost a few hours ago. Was my explanation clear? Do you have any more question that I can help answer?

**Comment by Sudip7** [comment]
@mmmavis : how to test this <Link to="/entry/120">Learn more</Link> in local environment. As http://localhost:3000/entry/120  has no meaning. So I may need to add a path that would work both in local as well as prod env.

**Comment by mmmavis** [comment]
@Sudip7 for this ticket specifically, we'll have to use `<a>` instead of `<Link>`. Reason for that is that the database we use for the production site (https://mozillapulse.org) is different from what we have for the staging site and our local env. As [`<Link>` is used to link to places **within** the application](https://github.com/ReactTraining/react-router/blob/v3/docs/API.md#link) and we can't guarantee entry id `120` on various database is the entry we want to link to, we'll have to use the typical anchor `<a href="https://www.mozillapulse.org/entry/120>Learn more</a>.` to link to it.

**Comment by Sudip7** [comment]
thanks @mmmavis , got the idea. will send the pull request today. hey @xmatthewx sorry for the delayed response.

**Comment by xmatthewx** [comment]
thanks @Sudip7 !

**Comment by mmmavis** [comment]
Live: https://www.mozillapulse.org/featured

Thanks @Sudip7 !
