### ISSUE TITLE
Seach keyboard on mobile should dismiss after hitting search/enter on keyboard

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#492]
From #419

### Action
On Mobile, hit search/enter key on keyboard

### Expected
Keyboard is dismissed

**Comment by mmmavis** [comment]
@kristinashu 

I just did some experiments for this... (for a more technical summary see https://github.com/mozilla/network-pulse/pull/677#issuecomment-325853073)

In short, we can turn the default "enter/return" key on mobile into "search/go". Tapping a "search/go" key reloads the page (i.e., it triggers the form's onsubmit event, see the technical summary for details) and that's why the keyboard gets dismissed.

I think page reloading isn't a good tradeoff for this, especially we are talking about mobile here. Guess we'll have to decide between one extra tap to dismiss the keyboard vs page reloading (though it's gonna be quick and lightweight usually... it takes extra time and bandwidth).

**Comment by xmatthewx** [comment]
Oye. Thanks for investigating @mmmavis. Introducing a page reload is a big tradeoff for dismissing the keyboard. Curious what @kristinashu thinks. 

I'm going to start a blog called "I can't believe the interweb hasn't figure this out yet." I'll add this and the anchor link + fixed header collision too.

**Comment by kristinashu** [comment]
Interesting, this is good to know! Thanks for getting to the bottom of it Mavis.

Let's avoid the page load. Closing this!

**Comment by xmatthewx** [comment]
It seems like @gvn had a suggestion that might help (unfocus before preventDefault). Worth trying @mmmavis?

**Comment by mmmavis** [comment]
@xmatthewx to me unfocus might not be good here as the search box "searches as you type". We probably don't wanna assume user has done typing and bring the focus away.

**Comment by xmatthewx** [comment]
right-o. we'll just have to live with this until the internet figures it out.

**Comment by gvn** [comment]
To clarify a bit: I was thinking you could unfocus when someone submits the form (eg: taps "enter" on mobile) to dismiss the keyboard. That would leave it open while someone is still typing...

So basically:

1. User types
2. User hits "enter"
3. In JS: prevent default from occurring on the submit event
4. In JS: unfocus the input
5. Keyboard should disappear

**Comment by xmatthewx** [comment]
I reopened this. Note, we can keep it out of this milestone and in the backlog while we discuss. It doesn't need to bump other priorities.
