### ISSUE TITLE
Add number of results for each issue tag

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#517]
@xmatthewx would you be up for adding something like this? This will be helpful feedback for users when one post appears at the top of several issues.

 https://redpen.io/qf3e141d69fb01cf4c

![issues results 2x](https://cloud.githubusercontent.com/assets/1068783/25675078/06771508-2ff2-11e7-9081-d050d64b234f.png)

**Comment by xmatthewx** [comment]
Yep. Great idea. Useful for search as well.

**Comment by Sudip7** [comment]
is this enhancement applicable for issues tab or for all the relevant tabs. Please clarify. @xmatthewx @kristinashu

**Comment by kristinashu** [comment]
Only in the Issues tab, thanks!

Note that search results already does this ([example](https://www.mozillapulse.org/search?keyword=design)), please style it the same.

**Comment by Sudip7** [comment]
Thanks @kristinashu . I added some code. Please, suggest should I add additional filters in order to restrict that to issue page or keep as it is.

![image](https://cloud.githubusercontent.com/assets/6715793/26260425/c8b58e7e-3cea-11e7-90ec-b042380a1e81.png)

![image](https://cloud.githubusercontent.com/assets/6715793/26260460/f5f3496c-3cea-11e7-9aef-7f9f0fcdc7a6.png)

![image](https://cloud.githubusercontent.com/assets/6715793/26260582/5ebfc024-3ceb-11e7-9e20-c543d413fa0b.png)


![image](https://cloud.githubusercontent.com/assets/6715793/26260524/2a3e8218-3ceb-11e7-89c0-9d471ce3c4f6.png)


@xmatthewx  @mmmavis  please suggest.

**Comment by kristinashu** [comment]
Yes, please hind on Featured and Latest pages. Thanks!

**Comment by xmatthewx** [comment]
👍  Yes. Please hide everywhere. Everywhere but individual issue pages. It could also show on individual tag views, for example: [/tags/mozfest](https://www.mozillapulse.org/tags/mozfest). But it shouldn't appear anywhere else.

**Comment by Sudip7** [comment]
I have added following code: 

reIssueCountResult() {
    if(this.props.latest) return null; 
    if(this.props.featured || this.props.search || this.state.loadingData) return null;
let total = this.state.totalMatched,
  plural = (total === 0 || total > 1), // because "0 results"
  issueCountResult = `${total} result${plural ? `s` : ``} found`;

return <p>{issueCountResult}</p>;
  },

Even though I added filter for latest tab, not sure why the count is still there. 

@xmatthewx @mmmavis please assist.

**Comment by mmmavis** [comment]
@Sudip7 which file(s) were you working on? We want to add the counter to [just the individual tag pages and issue pages](https://github.com/mozilla/network-pulse/issues/517#issuecomment-302813765). Take a look at `routes.jsx` and see what components `/tag` and `/issue/issue_name` are using. Those should be the components that we add the counter code to.

**Comment by mmmavis** [comment]
@Sudip7 do you wanna start a PR so I can check out your code and modified files?

**Comment by Sudip7** [comment]
@mmmavis , I have changed only one file project-loader.jsx. M sending the PR

**Comment by Sudip7** [comment]
@mmmavis any suggestions on fixing the problem??

**Comment by mmmavis** [comment]
Oops, this is done. Forgot to close this ticket.

**Comment by mmmavis** [comment]
https://www.mozillapulse.org/issues/online-privacy-and-security thanks @Sudip7
