### ISSUE TITLE
Remove URL share link

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#526]
We added in the link icon so users would know they could link directly to the post. Now that each post has it's own screen this is obvious, can we remove the link icon?

Do we have any analytics on the use of this link icon? 

As we add more features more and more features/content, we should remove any unnecessary info.

**Comment by xmatthewx** [comment]
Let's do that when we add a twitter share link. Save energy and keep the signal that these things are sharable until we get there. https://github.com/mozilla/network-pulse/issues/159

**Comment by mmmavis** [comment]
@kristinashu fyi, I just checked - that icon has only been clicked for 10 times so far. I agree we should remove it once we have the Twitter share icon in place.

**Comment by xmatthewx** [comment]
Hi. Totally agree to remove it. Just want to illustrate why we should dig deep with stats. 

It was used 14 times since the release to staff, which is 3 more times than the Get Involved link, arguably our most important action. The prominence of those actions and the status of the project (mostly internal use) deeply impact user behavior.

Of the 14 uses of the Link button, 3 were for project 177 (Call for Participation Now Open for the 2017 Digital Media & Learning Conference). Interestingly, this is our 4th most popular landing page for external links directly to projects. Incoming links are huge important, so low level use can still be valuable. 

Again, I think it's fine to remove. I'm very excited to leverage stats for deeper analysis once we have lots of network people looking.

**Comment by mmmavis** [comment]
Hey @xmatthewx I only know little about GA so I'm curious where on the dashboard I can find the info you mentioned above. 

From Behaviour -> Events -> Top Events, I only saw 10 "Entry Card - Reveal Entry Share Link" events
<img width="1146" alt="screen shot 2017-05-16 at 8 48 49 am" src="https://cloud.githubusercontent.com/assets/2896608/26115419/cbbf775c-3a14-11e7-9c88-5293a9ec85c7.png">

**Comment by xmatthewx** [comment]
I'm looking at the same view, starting at Apr 4th when we announced to staff. We can find some time to look at GA together. I'm not an expert, but have discovered a few useful things over the years.

**Comment by kristinashu** [comment]
I would also be curious how many of those clicks were from us QA-ing. The link was broken for a little while and then I think we were all testing it to make sure it was fixed.

**Comment by mmmavis** [comment]
Closing! The URL share button / field has been removed from the new 2-column detail view.
