### ISSUE TITLE
Update form for better tags

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#529]
Currently the same tag with different capitalization enters the DB as two different tags. Ex: DIY and diy. @alanmoo – do you think the form or the API should handle this?

- [x] On the form, we should update the label and hint. 
  - Form label: Tags: Comma separated. Spaces are ok. Issues are added automatically.
  - Placeholder: games, best practice, iot, cape town, code 
- [x] Bonus: Let's also put Issues before Tags on the form. A lot of people are adding issues as tags. It's unnecessary. 
- [ ] API convert tags lowercase https://github.com/mozilla/network-pulse-api/issues/115

**Comment by xmatthewx** [comment]
edited original comment

**Comment by alanmoo** [comment]
Ideally both should handle this, so that we don't have to worry about other uses of the API, but can also be clear about what the content will actually look like before it gets submitted. I envision an autocomplete component that converts the string to lowercase and puts a background on it when the user types a comma into the tag field. (So that it appears as a tag box representing the final project view as soon as possible.)

It feels like the API side is an easier change (probably one line of code somewhere), where the change to the front end would be made as part of the autocomplete component implementation.

**Comment by xmatthewx** [comment]
Ok. @mmmavis ticket will just be for form updates (copy and ordering listed above).

I've filed an API ticket and added a note to autocomplete ticket to convert to lowercase.

**Comment by mmmavis** [comment]
Todo item 1 and 2 are done. @xmatthewx I'll let you decide if we can close this ticket or not.

**Comment by xmatthewx** [comment]
Yes! thanks. the third is filed elsewhere.
