### ISSUE TITLE
Updates to entry view post-tags

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#532]
Some thoughts based on the new PR for tags on cards:

1. Should we update the API so it tells the front end how many entries are using a specific tag? That way we can only show tags that link to something other than just the current entry.

2. Should the Issues be rendered in a slightly different way than tags? From a messaging standpoint, it seems important to indicate they're special.

@mmmavis @kristinashu @xmatthewx

**Comment by mmmavis** [comment]
> 1. Should we update the API so it tells the front end how many entries are using a specific tag? That way we can only show tags that link to something other than just the current entry.

I like seeing all tags. As a user I would like to know what existing tags are out there already. Should we order the tags so that they are from most popular tag -> least popular?

2. Should the Issues be rendered in a slightly different way than tags? From a messaging standpoint, it seems important to indicate they're special.

+1 on this

**Comment by xmatthewx** [comment]
+1 ordering by frequency, subtly highlighting issue tags. I think we can keep this in the backlog for now.
