### ISSUE TITLE
Add GA event on "View More" buttons

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#566]
Knowing how many users tap a View More button for Featured and other views will help us understand browsing behavior better. Tracking this event will also help us distinguishes people who bounce quickly from those who spend a bit of time looking first. 

Category : Nav link
Action : Clicked
Label : [view] + 'more' (e.g. 'Featured more')

**Comment by mmmavis** [comment]
@xmatthewx I don't know what the best practices are for implementing GA events but I just wanna confirm that we want the `category` to be `Nav link` and not something like `View More button`? Currently clicking on any nav links will fire a GA event under the `Nav link` category with label being the `path` user is navigating to (e.g., `/latest`,  `/issues/`, etc)

**Comment by xmatthewx** [comment]
GA is weird in how it counts and organizes Events. I might be wrong about this, but it feels like the right way to organize it. Category is more about views in GA, than about aggregation. Or maybe both. 

Using the same Category allows us to see this list of actions in one view ... which is convenient in terms of understanding user intent:  
 - Featured
 - Featured view more
 - Issues

The actions themselves will still be counted separately.

**Comment by xmatthewx** [comment]
Behavior report is great, and we can already view that to include Pages and Events. 

I'm immensely curious how far people are browsing. So I'd like to get this in there as an event, regardless of how we label it. Any other suggestions? 

Google suggests using Categories fairly broadly to group things for reporting. ex: Category: Videos, Action: Play, Label: 'cat flip'. Play and Pause aren't Videos. They should have called it Group in instead of Category. In a sense, you are navigating to more content, navigating forward, rather than left or right. Same as if you navigated through a paginated report, or to the next aisle in a store. But... we actually don't need primary nav links as events since we can see that stuff as page views. We might have added them before since we didn't have routes and we were just filtering. 

So... we could pause to relabel and categorize all these things, but that'll take a little time. (I think I did a better job on the network site with an overall schema than I did on Pulse.)

I propose that we land this as described above or with another Category you think makes more sense. See how it feels. And then reorganize this stuff later. 

What do you think?

**Comment by mmmavis** [comment]
@xmatthewx I'll implement what you have suggested above so it doesn't block us from moving forward. One thing to bring up is that I noticed that we have started adding temporary quick fixes here and there so hopefully we can find time soon to tidy up this codebase a bit. Otherwise I'm worried these temporary things will bite us in the near future.

Questions about the GA event label: `Label : [view] + 'more' (e.g. 'Featured more')`. I don't wanna hard code a list of view names in so I think it'd best that's we just pass the url `path` as "view". 

for example:
1. https://www.mozillapulse.org/featured --> `view` = `/featured`
2. https://www.mozillapulse.org/latest --> `view` = `/latest`
3. https://www.mozillapulse.org/issues/decentralization --> `view` = `/issues/decentralization`
4. https://www.mozillapulse.org/search?keyword=mozfest --> `view` = `/search`

Looks good? We can also include query params as part of the `view` if you'd like.

**Comment by xmatthewx** [comment]
Using Path sounds good. 

We can pause this if you want, and take a look at how we handle all of these events. I started [a spreadsheet](https://docs.google.com/spreadsheets/d/1x-CP_HYaAs3oRv2cjbSFu8w5Z938E4cyHQ3hvh17c6c/edit#gid=1060389854) with some ideas, but feel free to propose alternatives. You'll see another tab for the network site.  

What are some of the other temporary fixes you're worried about? Feel free to file an issue to track that stuff.

**Comment by mmmavis** [comment]
Cool I can land this first and we will clean up GA labels in https://github.com/mozilla/network-pulse/issues/574
