### ISSUE TITLE
Optimize user image uploads

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#591]
Users will sometimes upload crazy big images. We should limit on kb and/or resolution if that isn't already in place.

@Pomax has a suggestion here: https://github.com/mozilla/network-pulse-api/issues/142#issuecomment-311442297

**Comment by Pomax** [comment]
For thimble we implemented this with some custom javascript that can be found in https://github.com/mozilla/brackets/blob/master/src/filesystem/impls/filer/lib/ImageResizer.js -- in order to adapt it for the Pulse client we would have to shim the bits of `pica`, which shouldn't be too much work (the only reason that code uses `pica` is because canvas does not work in a service worker, whereas for our Pulse client, which does not rely on service workers, that is not a concern)

**Comment by alanmoo** [comment]
@arush0311 this would be a great issue to work on

**Comment by arush0311** [comment]
Should we create a django widget for image field that take care of all this? I could also be combined with image preview!

**Comment by alanmoo** [comment]
Does something exist already that we could pull in, perhaps that supports queries/multiple versions for use in the `<picture>` element?

**Comment by arush0311** [comment]
>  supports queries/multiple versions for use in the <picture> element?
Do you want to upload multiple versions of a single image?

**Comment by alanmoo** [comment]
That's the idea- allow an editor to select what the cropping looks like at various breakpoints so we don't end up with someone's head being cropped out on small devices, for example.

**Comment by arush0311** [comment]
> so we don't end up with someone's head being cropped out on small devices, for example.
wouldn't we wanna resize the image (and not crop it on smaller devices?)

**Comment by alanmoo** [comment]
Not necessarily. See https://cloudfour.com/thinks/responsive-images-101-definitions/#artdirection

**Comment by Pomax** [comment]
@alanmoo @arush0311 we'll want to do this in a few steps, and not conflate the work involved with nice to haves:

1. see if there is already a django widget that does what we want. Even if we have "most of the code" already somewhere else, if *all* the code already exists as a django widget, we should just use that.

Failing that, the steps I see here are:

1. take the code and make it possible to pass in "pica" or "any other library with the same API" which in our case will be a thin wrapper around a plain canvas, and then turn that into a module of its own. This will let us file a refactor PR for @humphd so that we don't have two "nearly identical" files in two different repos that are used for the exact same thing.
2. first, update the template without creating a django widget: just add a script tag that loads the library, and then in the upload handler make sure its function gets called.
3. also, * don't* do any image modification such as cropping etc. The most pressing problem to solve is literally filesize, so let's preserve the current behaviour of the system and then we can contemplate exactly how to offer cropping etc controls to users in follow-up.

**Comment by humphd** [comment]
> take the code we wrote for brackets and turn it into a library that lets us pass in "pica" or "any other library with the same API" (which in our case will be a thin wrapper around a plain canvas) as well as an options object, and then turn that into a module of its own. This will let us file a refactor PR for @humphd so that we don't have two "nearly identical" files in two different repos that are used for the exact same thing.

https://github.com/humphd/brackets/blob/cb0c681f9b28115b97a50d6eb4730d6c37973560/src/filesystem/impls/filer/lib/ImageResizer.js is the bulk of that code, fwiw.

**Comment by ryanwarsaw** [comment]
Not getting to this before end of 2017 so removing myself for now.

**Comment by taisdesouzalessa** [comment]
Please note that the Profile pictures (for Fellows) used in Pulse are also being used in our Fellowship site's Directory:
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/22157921/37178662-073e3dde-22d8-11e8-9852-2db5173f7148.png">

Here are the specifications I used for those pictures:
- [ ] Square (600px X 600px) at 72ppi (pixels per inch)
- [ ] Saved for Web, JPEG, quality 80
- [ ] After saved, I used an image optimization tool to reduce their size even more. For mac users, I recommend: https://imageoptim.com/mac
