### ISSUE TITLE
add issue descriptions to individual issue pages

### ISSUE THREAD

**Issue by Pomax** [mozilla/network-pulse#597]
followup on #590: right now `/issues` will show name + desc, but `/issues/decentralization` etc. do not have a little heading with the description for decentralization.

**Comment by mmmavis** [comment]
+1 on this

@xmatthewx @kristinashu what do you think? If we all agree can I get a quick mockup for this?

**Comment by kristinashu** [comment]
I don't think it's necessary to show the description for decentralization on issues/decentralization. It's a nice intro to see it on /issues screen (we only added it to fill the blank space) but I think it's a little much to have on the actually content pages. It will push the key content down (especially on mobile).

**Comment by Pomax** [comment]
I'd like to raise two use cases that might not have been considered, though: it would be mighty helpful for people who are following any social media link that drops them straight into a specific issue. Seeing a lead-in text that explains what you're looking at is super valuable, rather than just seeing a grid of entries without any explanation of what this grid represents. The second use-case ties into that: especially if a news source ends up linking to one of our specific issue pages, we need to tell people what they're looking at. Especially for ESL users, but certainly also for native speakers, our issue labels are not straight forward, and explaining what we mean by them lets us clear up any confusion that might otherwise be vented on social media, comment threads, or in direct communication with us.

**Comment by xmatthewx** [comment]
Can I agree with both sides? 

I don't want to push down content since Pulse's primary audience is active participants and creators. The network site is better equipped to provide context and tell the bigger story for unacquainted visitors who are confused/interested. We could add a more info link at the top of pulse/issues/decentralization to the network site's [about page](https://network.mofoprod.net/about/). Jesse plan's to build out this page or another further, for an intro on internet health, issues, and other themes of focus (iot, open data). 

We also have shorter, more [plain language descriptions](Projects that help ensure that the internet is controlled by many, rather than just a handful of global technology giants.) on the network site for each issue. We should probably build a single place to store these key definitions.

**Comment by Pomax** [comment]
I'm mostly thinking of things where someone posts a link to our site on facebook or hackernews or the like. Even if it's not our intended audience, it feels like rather than "what am I looking at?" we want to illicit at least an "oh nice" reaction when a few thousand people click through =D

So as an idea: what if we add the description if the user is not logged in? Our "real" users will invariably already be logged in, so we can easily present them with the information they are clearly already interested in without the clutter of a lead-in paragraph. However, when you're not logged in, we can present that description blurb.

**Comment by kristinashu** [comment]
I like the idea of linking to the network sites about page since it is out of scope for Pulse to be really explaining our key issues and the network site is better equipped for that.

I also suspect that even if someone has clicked on a link to get to /decentralization then they would have some context from the tweet.

**Comment by Pomax** [comment]
Is there a (set of) tasks that we can turn this into for implementation purposes?
