### ISSUE TITLE
Enable Organization profiles

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#627]

**Comment by xmatthewx** [comment]
@kristinashu – it seems like organizations could use all the same fields as a user. no need for specialized form. true?

@alanmoo – if that's the case, i think we just need a way to identify whether a profile is a person or group. this should default to person, and only needs to be accessed via django for now. no specific use for it at this stage. if true, this can probably just be a note on the api model, rather than a separate ticket.

**Comment by kristinashu** [comment]
Yes, organizations and people have the same fields.

**Comment by xmatthewx** [comment]
This is noted in profile model. Pretty sure no work required beyond that. Closing.
