### ISSUE TITLE
Draft mockup of a "Collections" page

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/network-pulse#646]
Edit: I'd like to do a quick mockup, timeboxed to 2-3 hours, to help foster conversations with stakeholders. 

Background: Mozilla programs need to gather and present the people and projects impacted by the program. This serves recruitment, fundraising, reporting, and more. 

Idea: Enable an author to create a Page via CMS. Below their content, they can optionally specify a Pulse query to pull in Projects and/or Profiles. 

Continuing work in #630, we will synthesize input from stakeholders and explore UX of how that page renders. Should be kept simple, flexible. See [notes](https://docs.google.com/document/d/1dZ4ZwfTjJA_AdN8lWG3oW650e2-nPttg0rZmrGEFqGA/edit#) for more info.

**Comment by taisdesouzalessa** [comment]
Sketch from Matthew after our meeting:
<img width="846" alt="image" src="https://user-images.githubusercontent.com/22157921/29336830-0c912b80-81c4-11e7-8733-793860961c56.png">

Observations:
• As simple as opportunities Page - simple title, simple photo and a bunch of projects below
• Sample copy: "People are coming together in Mozfest to create projects that help ensure that the internet is controlled by many, rather than just a handful of global technology giants."

**Comment by taisdesouzalessa** [comment]
@xmatthewx here is the page's mockup: 
https://redpen.io/vzf9efadfec9443e15

**Comment by xmatthewx** [comment]
Perfect. Thanks. I'm going to close this and open a new epic to capture the related work.
