### ISSUE TITLE
Improve review app experience

### ISSUE THREAD

**Issue by alanmoo** [mozilla/network-pulse#730]
When a review app is created, it can't hook into the pulse staging api automatically due to approve-list requirements on the api. Is there anything we can do to automate/wildcard that approval?

Low priority.

**Comment by cadecairos** [comment]
I think what we need here is something like we have in network: 

https://github.com/mozilla/network/blob/6f8ec149d79bc1cb4f198edaebebf95679641e63/network-api/app/networkapi/settings.py#L378-L382

So that we can just whitelist all domains.

As it stands right now, I don't see any problem making our data available cross origin. if some random site starts using our data and DOSing pulseapi, then we can build something more robust.
