### ISSUE TITLE
UI: implement notification bar

### ISSUE THREAD

**Issue by kristinashu** [mozilla/network-pulse#740]
If a user has not been to /myprofile then we will show a notification.

This will appear on the following screens:
- add entry form
- add entry confirmation screen (both versions: staff and non-staff)

Links to profile form.

<img width="1063" alt="screen shot 2017-10-05 at 3 14 56 pm" src="https://user-images.githubusercontent.com/1068783/31255105-0b51031e-a9e0-11e7-8b7c-4e77129e9759.png">

@xmatthewx any copy suggestions?

**Comment by xmatthewx** [comment]
Two options:
 - "Add your profile[/myprofile] to show who's behind your great projects!"
 - "Add your profile[/myprofile] to connect, collaborate, and push your projects further."

**Comment by kristinashu** [comment]
Great! Let's go with "Add your profile [/myprofile] to show who's behind your great projects!"

Light purple is #EDE2FF

![post form with notification 2x](https://user-images.githubusercontent.com/1068783/31298710-43b6edc0-aaa0-11e7-8762-c95e6ee596ac.png)

**Comment by evgeny-petukhov** [comment]
@kristinashu May I work on this issue, please?

**Comment by xmatthewx** [comment]
> We could just make get the profile information for the user from the API and check

That's a good idea, especially if we can check _after_ the page is already loaded. 

Is the work worth it? I think yes. Of all the people who have logged in during the past 90 days, nearly 2/3 have both twitter _and_ bio blank.

**Comment by mmmavis** [comment]
FYI we already have a `NotificationBar` component: https://github.com/mozilla/network-pulse/tree/master/components/notification-bar

@xmatthewx do we have stats about how many people actually click on their name at top right to go to their own profile? I wonder if it makes more sense to just make the "please complete your profile" prompt more obvious on user's own profile page instead of showing a notification bar on the "add a new project" page since that can disrupt that the user is trying to do (i.e., from adding a new entry -> editing profile)

**Comment by jamilasnell** [comment]
Closing this until we decide to work on pulse again
