### ISSUE TITLE
Bug: Issue tags on Profile page are mapped to wrong urls

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network-pulse#787]
Once I see my profile and click on one of the interests, I am taken to a new page that filters posts related to that interest. My expectation would be to have it highlighted at the top so I feel sure the posts are filtered according to the issue I am interested on: "Decentralization", "Digital Inclusion" and so on.

![pulse](https://user-images.githubusercontent.com/22157921/31901663-f0da4fae-b7d6-11e7-8752-59db36dd8e37.gif)

**Comment by xmatthewx** [comment]
Interesting. Good catch. It works if you tap an Issue on a project card, but not on a profile. 

Note: this is not critical. It can wait until post-MozFest.

**Comment by mmmavis** [comment]
Currently only the 5 child routes under `/issues/` will load projects of a particular internet health issue as expected. Any other route under `/issues/` will just load all projects on Pulse.

- /issues/online-privacy-and-security
- /issues/open-innovation
- /issues/decentralization
- /issues/web-literacy
- /issues/digital-inclusion


Issue tags on profile page link to `/issues/<issue name>` directly without mapping them to the routes above (e.g., https://www.mozillapulse.org/issues/Online%20Privacy%20%26%20Security ). That's why none of those issue button is highlighted (unknown url param) and the page shows you ALL Pulse projects.

**Comment by mmmavis** [comment]
I filed a PR to fix the bug on profile page. [Followup ticket](https://github.com/mozilla/network-pulse/issues/852) has been filed so let's discussion there what long term solution we wanna go for.

**Comment by mmmavis** [comment]
Fixed.
