### ISSUE TITLE
Add background-blend-mode to uploaded images

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#792]
Looking through a single column list of entries can sometimes be visually confusing, as the images for the entries might have white backgrounds with text. It really breaks up the visual flow, see below...

![image](https://user-images.githubusercontent.com/25212/31902108-8d751c26-b7d8-11e7-9ba9-34249872c10f.png)

One way to address this would be to add a faint grey border around the images or maybe some horizontal dividers.

**Comment by mmmavis** [comment]
@kristinashu thoughts? 😃

**Comment by kristinashu** [comment]
I think this is only an issue when the images either:
a) the wrong aspect ratio or
b) on a white background

Solution for a) 
We have since solved for the wrong aspect ratio by added grey sides to image that need it. 

Solution for b) 
For images on a white background, would it be possible to make them look like they are on a light grey background by multiplying a light grey over top of the image? Guess we would need to do this to all images, which is ok with me. Is this technically possible? Any concerns with doing it?

Example:
![screen-shot-2017-11-27-at-2 44 47-pm](https://user-images.githubusercontent.com/1068783/33294806-1ef85892-d387-11e7-8783-d8e7fab6f7f1.png)

**Comment by flukeout** [comment]
Hey @mmmavis & @kristinashu—I think this is a pretty cool solution and can be achieved by using background-blend-mode in CSS, as described [here](https://css-tricks.com/basics-css-blend-modes/). The problem is that it is not supported in IE.

Unless we get really fancy, we won't know which photos to use this on, so we'll probably have to do it to all of them, meaning they will all be _slightly_ darker.

I think it's worth trying out, and at least it will look nicer for non-IE users.

**Comment by kristinashu** [comment]
Cool! Thanks for looking into it. I'm good with using this effect on all images. Also ok that it won't work on IE. Oh IE!

**Comment by mmmavis** [comment]
This is done!
