### ISSUE TITLE
Long names issue on mobile

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/network-pulse#799]
If a user have a long name, it displays on top of the logo instead of breaking into 2 lines:

![img_6097](https://user-images.githubusercontent.com/22157921/31902863-2b6378ae-b7db-11e7-88ba-125107753a0a.PNG)

**Comment by taisdesouzalessa** [comment]
@xmatthewx assigning it to you so you can add the labels and priority as you see fit.

**Comment by mmmavis** [comment]
Should we clip it or wrap it to the next line?

**Comment by xmatthewx** [comment]
Let's clip it. 

@kristinashu - if you have a better idea, jump in. Otherwise @mmmavis, in the interest of time and simplicity, let's just run with mockup below. 

I think we can remove the comma too, to save on space. 

![image](https://user-images.githubusercontent.com/53411/31910027-1f858764-b80a-11e7-9865-9270599536bc.png)

**Comment by xmatthewx** [comment]
this is done. looks great. thanks!
