### ISSUE TITLE
Staging QA: Link URLs in copy added by users?

### ISSUE THREAD

**Issue by flukeout** [mozilla/network-pulse#802]
The Get Involved section for https://www.mozillapulse.org/entry/483 has a URL in the copy. It would be nice if we converted it to a clickable link.

![image](https://user-images.githubusercontent.com/25212/31903150-21fdd902-b7dc-11e7-9a26-609ffb54107c.png)

**Comment by shikhar-scs** [comment]
@flukeout I would like to take up this issue. May I ?

**Comment by xmatthewx** [comment]
@shikhar-scs thanks for offering! We are not ready to take on this issue because it introduces too much questions and complexity in terms of pattern matching, user intent, and how we store the data. 

Take a look at issues with the label [good first issue](https://github.com/mozilla/network-pulse/labels/good%20first%20issue) or [help wanted](https://github.com/mozilla/network-pulse/labels/help%20wanted).

**Comment by alanmoo** [comment]
You can give it a shot if you'd like, no guarantees we'll merge it in though. What approach are you thinking of taking? There's a bunch of directions this could go.

**Comment by shikhar-scs** [comment]
Yeah Sure, I'll post my approach soon

**Comment by xmatthewx** [comment]
@alanmoo - as we look to use the API by more than one resource, you should probably decide if we want to process inline URLs during submission. Otherwise we risk a future need to maintain this across multiple sites. 

Since we're looking at markdown for other uses, we might want to wait until we land that, and see if that's a better solution. I checked, and we see urls in 2-4% of entries. So this would be useful for sure, but not critical.

**Comment by shikhar-scs** [comment]
After searching the files for a while, I found that the following piece of code is responsible for generating the paragraph related to get involved. 

https://github.com/mozilla/network-pulse/blob/master/components/project-card/meta/get-involved.jsx#L19-L46

But
![codeisscience](https://user-images.githubusercontent.com/25258877/34706112-422e4824-f52b-11e7-894f-002b284f847c.png)
 I dont know exactly where the exact hardcoded string of `props.getInvolvedText` exists. 
What I thought is that the part of the string which reads `http://www.codeisscience.com/` in `props.getInvolvedText` can be replaced with `codeisscience.com` to improve readability and subsequently the text which reads `Get Involved` in the end of `props.getInvolvedText` , rendered by this line
` this.handleGetInvolvedLinkClick()}>Get Involved</a>) :` .

can be changed to `Visit codeisscience.com`

This is what I think. Rest is up to the mentors, whatever they think is better. :smiley:

**Comment by alanmoo** [comment]
Those strings are coming from the user submitted database, so we can’t enforce a format for the links in the free text area, and we can’t manually add anchor tags to links. If you have a suggestion for how to do it in react, I’m all ears, but keep in mind the performance impact of running every string through a parser.

**Comment by shikhar-scs** [comment]
> Those strings are coming from the user submitted database, so we can’t enforce a format for the links in the free text area

Oh, I didnt know that. Well this is a lot trickier than I thought it would have been. Also, being a newbie I dont know much about react. Apologies for wasting everyone's time. Ill look out for something else. :+1:

**Comment by xmatthewx** [comment]
No problem! Thanks @shikhar-scs we appreciate your interest and we're glad to help orient you. 

We have flagged issues with the label [good first issue](https://github.com/mozilla/network-pulse/labels/good%20first%20issue) or [help wanted](https://github.com/mozilla/network-pulse/labels/help%20wanted) because they are particularly good for contributors who are getting familiar with the project and our workflow.
